version: 2
updates:
  - package-ecosystem: gomod
    directory: /
    schedule:
      interval: weekly
    open-pull-requests-limit: 5
  - package-ecosystem: npm
    directory: /web
    schedule:
      interval: weekly
    open-pull-requests-limit: 5
    groups:
      ai-sdk:
        patterns:
          - ai
          - '@ai-sdk/*'
      react:
        patterns:
          - react
          - react-dom
          - '@types/react'
          - '@types/react-dom'
      localization:
        patterns:
          - i18next
          - react-i18next
  - package-ecosystem: github-actions
    directory: /
    schedule:
      interval: weekly
    open-pull-requests-limit: 5
