import {SourceProgress,occurrenceState} from './SourcePreparations'
import { deskEventPath } from '../desks/scope'
import { useDirtyGuard } from '../shell/useDirtyGuard'
import { useConfirmDiscard } from '../shell/UnsavedChanges'
import {useRef,useState} from 'react'
import {useInfiniteQuery,useQuery,useQueryClient} from '@tanstack/react-query'
import {Link} from 'react-router-dom'
import {formatDate,msg} from '../i18n'
import type {PackDocument} from '../mcp/types'
import {Button} from '../ui/Button'
import {Select} from '../ui/Select'
import {Input} from '../ui/Input'
import {Disclosure} from '../ui/Disclosure'
import {Dialog,DialogActions} from '../ui/Dialog'
import {Tooltip} from '../ui/Tooltip'
import {jobsAPI,type Page,type Release} from './client'
import {defaultTrigger,TriggerForm,triggerName} from './TriggerForm'
import type {Occurrence,Trigger,TriggerConfig} from './triggerTypes'
import styles from './JobsView.module.css'

type Preview={config?:TriggerConfig;next:string[];inputReady:boolean;configurationReady?:boolean;deferred?:boolean;factsText?:string;evidenceText?:string}
const when=(s:string)=>formatDate(new Date(s),{dateStyle:'medium',timeStyle:'short'})
export function triggerState(t:Pick<Trigger,'paused'|'config'|'nextAt'|'problem'>){return t.paused?msg('Paused'):t.problem?msg('Needs attention'):t.config.kind==='cloud'?msg('Listening'):t.config.kind==='schedule'&&!t.nextAt?msg('Finished'):msg('Active')}
function failure(e:unknown){return e instanceof Error?e.message:String(e)}
function reason(value?:string){return value?({'missed':msg('Missed while unavailable'),'latest-after-missed':msg('Latest missed occurrence'),'overlap':msg('Another run was pending'),'queue-full':msg('Queue full'),'queue-expired':msg('Queue expired'),'trigger-paused':msg('Trigger paused')} as Record<string,string>)[value]??value:'—'}
export function TriggersView({jobId,release}:{jobId:string;release:Release}){
 const client=useQueryClient(),opener=useRef<HTMLElement|null>(null)
 const query=useQuery({queryKey:['job-triggers',jobId],queryFn:()=>jobsAPI<{items:Trigger[];localFiles:boolean}>(`jobs/${jobId}/triggers`),refetchInterval:5000})
 const history=useInfiniteQuery({queryKey:['job-occurrences',jobId],initialPageParam:0,queryFn:({pageParam})=>jobsAPI<Page<Occurrence>>(`jobs/${jobId}/occurrences?after=${pageParam}`),getNextPageParam:p=>p.next||undefined,refetchInterval:5000})
 const [kind,setKind]=useState<TriggerConfig['kind']>('schedule'),[edit,setEdit]=useState<{id?:string;revision?:number;config:TriggerConfig}>(),[valid,setValid]=useState(false)
 const [busy,setBusy]=useState(false),[error,setError]=useState(''),[preview,setPreview]=useState<Preview>(),[review,setReview]=useState<{trigger:Trigger;rotate?:boolean}>(),[reviewed,setReviewed]=useState(false),[reviewPreview,setReviewPreview]=useState<Preview>(),[reviewError,setReviewError]=useState('')
 const [secret,setSecret]=useState<{id:string;token:string}>(),[copied,setCopied]=useState(false)
 const [unwritten,setUnwritten]=useState(false)
 const baseline=useRef(''),confirmDiscard=useConfirmDiscard()
 const dirty=!!edit && (unwritten || JSON.stringify(edit.config)!==baseline.current)
 useDirtyGuard(dirty,msg('Discard unsaved trigger changes?'),{name:edit?.config.name,busy,shouldBlock:({currentLocation,nextLocation})=>currentLocation.pathname!==nextLocation.pathname || new URLSearchParams(nextLocation.search).get('tab')!=='triggers' || new URLSearchParams(nextLocation.search).get('run')==='new'})
 const doc=JSON.parse(release.pack) as PackDocument
 const refresh=()=>Promise.all([client.invalidateQueries({queryKey:['job-triggers',jobId]}),client.invalidateQueries({queryKey:['job-occurrences',jobId]}),client.invalidateQueries({queryKey:['jobs-pages']})])
 async function save(){if(!edit||!valid)return;setBusy(true);setError('');try{await jobsAPI(`jobs/${jobId}/triggers`,edit);setEdit(undefined);setPreview(undefined);await refresh()}catch(e){setError(failure(e))}finally{setBusy(false)}}
 async function check(){if(!edit)return;setBusy(true);setError('');setPreview(undefined);try{setPreview(await jobsAPI<Preview>(`jobs/${jobId}/triggers/preview`,edit.config))}catch(e){setError(failure(e))}finally{setBusy(false)}}
 async function pause(t:Trigger){setBusy(true);setError('');try{await jobsAPI(`triggers/${t.id}/state`,{revision:t.revision,paused:true});await refresh()}catch(e){setError(failure(e))}finally{setBusy(false)}}
 async function openReview(t:Trigger,element:HTMLElement,rotate=false){opener.current=element;setReview({trigger:t,rotate});setReviewed(false);setReviewError('');setReviewPreview(undefined);if(rotate||t.config.kind==='event')return;setBusy(true);try{setReviewPreview(await jobsAPI<Preview>(`jobs/${jobId}/triggers/preview`,t.config))}catch(e){setReviewError(failure(e))}finally{setBusy(false)}}
 async function activate(){if(!review||!reviewed)return;setBusy(true);setReviewError('');try{const response=await jobsAPI<{trigger:Trigger;token:string}>(`triggers/${review.trigger.id}/${review.rotate?'rotate-key':'state'}`,{revision:review.trigger.revision,...(!review.rotate?{paused:false,reviewed:true}:{})});await refresh();setReview(undefined);if(response.token){setSecret({id:response.trigger.id,token:response.token});setCopied(false)}}catch(e){setReviewError(failure(e))}finally{setBusy(false)}}
 const items=query.data?.items??[],occurrences=history.data?.pages.flatMap(p=>p.items)??[]
 return <div className={styles.stack}>
  <div className={styles.readinessHeading}><h2>{msg('Triggers')}</h2><div className={styles.actions}><Select id="new-trigger-kind" aria-label={msg('Trigger type')} value={kind} disabled={busy||Boolean(edit)} options={(['schedule','file','event','cloud'] as const).map(value=>({value,label:triggerName(value)}))} onValueChange={v=>setKind(v as TriggerConfig['kind'])}/><Button disabled={busy||Boolean(edit)} onClick={()=>{baseline.current=JSON.stringify(defaultTrigger(kind,release.inputMapping));setEdit({config:JSON.parse(baseline.current) as TriggerConfig});setError('');setPreview(undefined)}}>{msg('Add trigger')}</Button></div></div>
  <p className={styles.note}>{msg('Local runner · Desk must be running and this computer must be awake. Triggers continue without an open browser.')}</p>
  {(error||query.error)&&<p role="alert" className={styles.problem}>{error||failure(query.error)}</p>}
  {query.isPending&&<p role="status">{msg('Loading…')}</p>}
  {!query.isPending&&!query.error&&!items.length&&!edit&&<p className="quiet">{msg('No automatic triggers. You can run this job manually or through the API.')}</p>}
  {items.length>0&&<div className={styles.tableWrap}><table className={styles.table}><thead><tr><th>{msg('Trigger')}</th><th>{msg('Status')}</th><th>{msg('Next run')}</th><th><span className="sr-only">{msg('Actions')}</span></th></tr></thead><tbody>{items.map(t=><tr key={t.id}><td>{t.config.name}{t.config.name!==triggerName(t.config.kind)&&<span className={styles.cellMeta}>{triggerName(t.config.kind)}</span>}{t.problem&&<span className={`${styles.cellMeta} ${styles.problem}`}>{t.problem}</span>}</td><td>{triggerState(t)}</td><td>{t.nextAt?when(t.nextAt):t.config.kind==='cloud'?msg('Managed in Google Cloud'):'—'}{t.config.schedule&&<span className={styles.cellMeta}>{t.config.schedule.timezone}</span>}</td><td><div className={styles.actions}><Button variant="quiet" disabled={busy||Boolean(edit)} onClick={()=>{baseline.current=JSON.stringify(t.config);setEdit({id:t.id,revision:t.revision,config:structuredClone(t.config)});setPreview(undefined);setError('')}}>{msg('Edit')}</Button>{t.paused?<Button disabled={busy||Boolean(edit)} onClick={e=>void openReview(t,e.currentTarget)}>{msg('Enable')}</Button>:t.config.kind==='schedule'&&!t.nextAt?null:<Button disabled={busy||Boolean(edit)} onClick={()=>void pause(t)}>{msg('Pause')}</Button>}</div>{t.config.kind==='event'&&<Disclosure title={msg('Event endpoint')}><pre className={styles.json}>{`${location.origin}${deskEventPath(t.id)}`}</pre><p className={styles.note}>{msg('Send a POST with Authorization: Bearer and the trigger token. Include a unique id, occurredAt timestamp and input object. Retry identical deliveries with the same id.')}</p><pre className={styles.json}>{`GET ${location.origin}${deskEventPath(t.id)}/occurrences/occ_<id>`}</pre><p className={styles.note}>{msg("The token that delivered an event can read that occurrence's result here: send a GET with the same Authorization header and the occurrence id from the delivery's response. Send it from a program, not a browser.")}</p>{t.hasKey&&<Button variant="quiet" disabled={busy} onClick={e=>void openReview(t,e.currentTarget,true)}>{msg('Rotate token')}</Button>}</Disclosure>}</td></tr>)}</tbody></table></div>}
  {edit&&<section className={styles.runForm}><h2>{edit.id?msg('Edit trigger'):msg('Add trigger')}</h2><TriggerForm key={edit.id??kind} doc={doc} mapping={release.inputMapping} value={edit.config} disabled={busy} onValid={setValid} onUnwritten={setUnwritten} onChange={config=>{setEdit({...edit,config});setPreview(undefined)}}/>{preview&&<PreviewResult value={preview}/>}<div className={styles.actions}><Button disabled={busy} onClick={async()=>{if(dirty&&!await confirmDiscard(msg('Discard unsaved trigger changes?'),{name:edit.config.name,busy}))return;setEdit(undefined);setPreview(undefined);setError('')}}>{msg('Cancel')}</Button><Button disabled={busy||!valid} onClick={()=>void check()}>{msg('Preview trigger')}</Button><Button variant="primary" disabled={busy||!valid} onClick={()=>void save()}>{msg('Save paused')}</Button></div></section>}
  <section className={styles.stack}><h2>{msg('Trigger history')}</h2><p className={styles.note}>{msg('Every occurrence records its admission separately from the run result. Skipped or expired occurrences do not evaluate the pack.')}</p>{history.error&&<p role="alert" className={styles.problem}>{failure(history.error)}</p>}{!history.isPending&&!history.error&&!occurrences.length&&<p className="quiet">{msg('No occurrences yet')}</p>}{occurrences.length>0&&<div className={styles.tableWrap}><table className={styles.table}><thead><tr><th>{msg('Trigger')}</th><th>{msg('Received')}</th><th>{msg('Admission')}</th><th>{msg('Details')}</th><th>{msg('Run')}</th></tr></thead><tbody>{occurrences.map(o=><tr key={o.id}><td>{items.find(t=>t.id===o.triggerId)?.config.name??triggerName(o.kind)}</td><td>{when(o.receivedAt)}</td><td>{occurrenceState(o.state)}</td><td>{o.preparation?<SourceProgress occurrence={o}/>:reason(o.reason)}{o.missedFrom&&<span className={styles.cellMeta}>{when(o.missedFrom)} → {when(o.missedThrough??o.missedFrom)}</span>}</td><td>{o.runId?<Link to={`/jobs/${jobId}/runs/${o.runId}`}>{o.runId.slice(-8)}</Link>:'—'}</td></tr>)}</tbody></table></div>}{history.hasNextPage&&<div><Button disabled={history.isFetchingNextPage} onClick={()=>void history.fetchNextPage()}>{msg('Load more')}</Button></div>}</section>
  <Dialog open={Boolean(review)} onOpenChange={open=>{if(!open&&!busy)setReview(undefined)}} title={review?.rotate?msg('Rotate event token'):msg('Enable trigger')} openerRef={opener} footer={<DialogActions><Button disabled={busy} onClick={()=>setReview(undefined)}>{msg('Cancel')}</Button><Button variant="primary" disabled={busy||!reviewed||Boolean(review&&!review.rotate&&(review.trigger.config.kind==='schedule'||review.trigger.config.kind==='cloud')&&!(reviewPreview?.inputReady||reviewPreview?.configurationReady))} onClick={()=>void activate()}>{review?.rotate?msg('Rotate token'):msg('Enable')}</Button></DialogActions>}>
   {review&&<div className={styles.stack}><strong>{review.trigger.config.name}</strong>{review.trigger.problem&&<p role="alert" className={styles.problem}>{review.trigger.problem}</p>}{review.rotate?<p>{msg('The previous token will stop working immediately. Update every sender with the replacement token.')}</p>:<><TriggerSummary config={review.trigger.config}/>{reviewPreview&&<PreviewResult value={reviewPreview}/>}<p className={styles.note}>{review.trigger.config.kind==='file'?msg('Existing content becomes the baseline. A missing file is allowed; the first stable arrival will trigger a run.'):msg('Future occurrences will run with these inputs and this fixed release. Pausing later stops new occurrences; accepted work continues.')}</p></>}{busy&&<p role="status">{msg('Checking…')}</p>}{reviewError&&<p role="alert" className={styles.problem}>{reviewError}</p>}<label className="checkbox"><input type="checkbox" checked={reviewed} disabled={busy} onChange={e=>setReviewed(e.target.checked)}/>{msg('I reviewed this trigger and its execution policy.')}</label></div>}
  </Dialog>
  <Dialog open={Boolean(secret)} onOpenChange={open=>{if(!open)setSecret(undefined)}} title={msg('Event token')} openerRef={opener} footer={<DialogActions><Button onClick={()=>setSecret(undefined)}>{msg('Done')}</Button></DialogActions>}>
   {secret&&<div className={styles.stack}><p>{msg('Copy this token now. It is shown once and only authorizes deliveries to this trigger.')}</p><Input aria-label={msg('Event token')} readOnly value={secret.token}/><Tooltip content={msg('Copy token to clipboard')}><Button onClick={()=>void navigator.clipboard.writeText(secret.token).then(()=>setCopied(true)).catch(()=>setCopied(false))}>{copied?msg('Copied'):msg('Copy token')}</Button></Tooltip><pre className={styles.json}>{`POST ${location.origin}${deskEventPath(secret.id)}\nAuthorization: Bearer <token>\nContent-Type: application/json\n\n{"id":"unique-delivery-id","occurredAt":"<current RFC3339 timestamp>","input":{"facts":{}}}`}</pre><p className={styles.note}>{msg('Use the release mapping for mapped inputs. Deliver within five minutes; an identical retry returns the original occurrence.')}</p></div>}
  </Dialog>
 </div>
}
export function TriggerSummary({config}:{config:TriggerConfig}){
 return <dl className={styles.properties}><div><dt>{msg('Trigger')}</dt><dd>{config.name}{config.name!==triggerName(config.kind)&&<> · {triggerName(config.kind)}</>}</dd></div>{config.schedule&&<><div><dt>{msg('Time zone')}</dt><dd>{config.schedule.timezone}</dd></div><div><dt>{msg('Start')}</dt><dd>{formatDate(new Date(config.schedule.startAt),{dateStyle:'medium',timeStyle:'short',timeZone:config.schedule.timezone})}</dd></div></>}{config.cloud&&<><div><dt>{msg('Cloud connection')}</dt><dd>{config.cloud.connection}</dd></div><div><dt>{msg('Scheduler job name')}</dt><dd>{config.cloud.job}</dd></div></>}{config.input&&<div><dt>{msg('Inputs')}</dt><dd>{config.input.kind==='mapped-sources'?msg('Fresh Gateway operations'):config.input.kind==='constant'?msg('Explicit constants'):[config.input.path,...Object.values(config.input.files??{})].filter(Boolean).join(', ')}</dd></div>}{config.watchPath&&<div><dt>{msg('Watch file')}</dt><dd>{config.watchPath}</dd></div>}{(config.kind==='schedule'||config.kind==='cloud')&&<div><dt>{msg('Missed runs')}</dt><dd>{config.missed==='skip'?msg('Skip missed runs'):config.kind==='cloud'?msg('Deliver before expiry'):msg('Run latest once')}</dd></div>}<div><dt>{msg('While another run is pending')}</dt><dd>{config.overlap==='skip'?msg('Skip this occurrence'):msg('Queue this occurrence')}</dd></div>{Boolean(config.preparationSeconds)&&<div><dt>{msg('Source wait (minutes)')}</dt><dd>{(config.preparationSeconds??3600)/60}</dd></div>}<div><dt>{msg('Queue expiry (minutes)')}</dt><dd>{config.queueSeconds/60}</dd></div></dl>
}
function PreviewResult({value}:{value:Preview}){return <div className={styles.stack}>{value.deferred&&<p className={styles.note}>{msg('Configuration checked. Sources will be fetched when the trigger runs.')}</p>}{value.next.length>0&&<div><h3>{msg('Next occurrences')}</h3><ul>{value.next.map(t=><li key={t}>{formatDate(new Date(t),{year:'numeric',month:'short',day:'numeric',hour:'numeric',minute:'2-digit',timeZoneName:'longOffset',timeZone:value.config?.schedule?.timezone??'UTC'})}</li>)}</ul></div>}{value.inputReady&&<Disclosure title={msg('Input preview')}><pre className={styles.json}>{value.factsText}</pre>{value.evidenceText&&<pre className={styles.json}>{value.evidenceText}</pre>}</Disclosure>}</div>}
