import {act,cleanup,fireEvent,render,screen,waitFor,within} from '@testing-library/react'
import {QueryClientProvider} from '@tanstack/react-query'
import {useState} from 'react'
import {RouterProvider,createMemoryRouter} from 'react-router-dom'
import {afterEach,expect,it,vi} from 'vitest'
import {testQueryClient,connected,stubClient} from '../../testing/harness'
import {McpContext} from '../../mcp/McpProvider'
import {PacksLayout} from '../../routes/PacksLayout'
import {applyFolderAction,defaultFolders,FOLDERS_FILE,HOME_FOLDER} from './model'
import {FOLDERS_KEY,loadFolders,saveFolderAction,assignCreatedPack} from './client'
vi.mock('./client',async original=>({...await original<typeof import('./client')>(),loadFolders:vi.fn(),saveFolderAction:vi.fn(),assignCreatedPack:vi.fn()}))
afterEach(()=>{cleanup();vi.restoreAllMocks();vi.clearAllMocks();vi.unstubAllGlobals();localStorage.clear()})
function setup({width=1100,path='/packs',corrupt=false,rootPending=false,graphs=false,state=undefined as unknown}={}){
 const observers:{callback:(entries:ResizeObserverEntry[])=>void}[]=[]
 vi.stubGlobal('ResizeObserver',class {constructor(callback:(entries:ResizeObserverEntry[])=>void){observers.push({callback})} observe(){} disconnect(){} unobserve(){}})
 vi.spyOn(HTMLElement.prototype,'getBoundingClientRect').mockImplementation(()=>({x:0,y:0,top:0,left:0,bottom:700,right:width,width,height:700,toJSON(){}}))
 let document=applyFolderAction(applyFolderAction(defaultFolders(),{type:'create',id:'dept',name:'Operations',parentId:HOME_FOLDER}),{type:'create',id:'child',name:'Intake',parentId:'dept'})
 document=applyFolderAction(document,{type:'assign',packId:'department-pack',folderId:'child'})
 vi.mocked(loadFolders).mockImplementation(async()=>{if(corrupt)throw new Error('Unreadable');return {document,digest:'read'}})
 vi.mocked(saveFolderAction).mockImplementation(async(before,action)=>{document=applyFolderAction(before.document,action);return {document,digest:'saved'}})
 const client=testQueryClient();if(!rootPending)client.setQueryData(['desk-files'],{root:'/project',files:[{path:FOLDERS_FILE,bytes:1,sha256:'read'}]})
 const stub=stubClient({experimental_list_graphs:()=>({text:JSON.stringify({status:'valid',graphs:[{id:'flow',graphVersion:'1.0.0'}]})}),list_packs:()=>({text:JSON.stringify({status:'valid',packs:[{id:'home-pack',packVersion:'1'},{id:'department-pack',packVersion:'1'}]})})})
 const router=createMemoryRouter([{path:'/packs',element:<McpContext.Provider value={connected({client:stub.client,graphInventorySupported:graphs})}><PacksLayout/></McpContext.Provider>,children:[{path:':packId',element:<><p>Pack content</p><Editable/></>}]},{path:'/create-pack',element:<p>Create</p>}],{initialEntries:[{pathname:path,state}]})
 render(<QueryClientProvider client={client}><RouterProvider router={router}/></QueryClientProvider>)
 return {client,router,resize:(next:number)=>{width=next;act(()=>observers.forEach(observer=>observer.callback([])))}}
}
async function newFolder(){fireEvent.keyDown(screen.getByRole('button',{name:'Collection options'}),{key:'Enter'});fireEvent.click(await screen.findByRole('menuitem',{name:'New folder'}))}
function Editable(){const [value,setValue]=useState('');return <input aria-label="Unfinished edit" value={value} onChange={event=>setValue(event.target.value)}/> }
it('defaults existing packs to home, scopes nested search, and carries destination into creation',async()=>{
 const {router}=setup()
 await screen.findByRole('link',{name:/home-pack/})
 expect(screen.queryByRole('link',{name:/department-pack/})).toBeNull()
 fireEvent.change(screen.getByRole('searchbox',{name:'Search packs and graphs'}),{target:{value:'department'}})
 await screen.findByRole('link',{name:/department-pack/})
 fireEvent.change(screen.getByRole('searchbox',{name:'Search packs and graphs'}),{target:{value:''}})
 fireEvent.click(within(screen.getByRole('navigation',{name:'Folder navigation'})).getByRole('button',{name:'Operations'}))
 fireEvent.keyDown(screen.getByRole('button',{name:'Create'}),{key:'Enter'})
 expect((await screen.findByRole('menuitem',{name:'Create pack'})).getAttribute('href')).toBe('/packs/new?folder=dept')
 fireEvent.keyDown(screen.getByRole('menu'),{key:'Escape'})
 fireEvent.click(within(screen.getByRole('list',{name:'Subfolders'})).getByRole('button',{name:'Intake'}))
 await screen.findByRole('link',{name:/department-pack/})
 expect(screen.queryByRole('link',{name:/home-pack/})).toBeNull()
 fireEvent.click(screen.getByRole('link',{name:/department-pack/}))
 await screen.findByText('Pack content')
 expect(screen.queryByRole('navigation',{name:'Folder navigation'})).toBeNull()
 fireEvent.click(screen.getByRole('button',{name:'Expand folders'}))
 fireEvent.click(within(screen.getByRole('navigation',{name:'Folder navigation'})).getByRole('button',{name:'Operations'}))
 expect(router.state.location.pathname).toBe('/packs')
})
it('creates an empty folder in a modal and preserves it in the hierarchy',async()=>{
 const {client}=setup()
 await screen.findByRole('link',{name:/home-pack/})
 await newFolder()
 expect(screen.getByRole('dialog',{name:'New folder'})).toBeTruthy()
 fireEvent.change(screen.getByRole('textbox',{name:'Folder name'}),{target:{value:'Finance'}})
 fireEvent.click(screen.getByRole('button',{name:'Create folder'}))
 await waitFor(()=>expect(saveFolderAction).toHaveBeenCalledOnce())
 await waitFor(()=>expect(screen.getAllByRole('button',{name:'Finance'}).length).toBeGreaterThan(0))
 expect(client.getQueryData<{document:{folders:{name:string}[]}}>(FOLDERS_KEY)?.document.folders.some(folder=>folder.name==='Finance')).toBe(true)
})
it('resizes by keyboard, remembers collapse, and restores the folder browser',async()=>{
 setup();await screen.findByRole('link',{name:/home-pack/})
 const separator=screen.getByRole('separator',{name:'Resize folder pane'})
 fireEvent.keyDown(separator,{key:'ArrowRight'})
 expect(separator.getAttribute('aria-valuenow')).toBe('228')
 fireEvent.click(screen.getByRole('button',{name:'Collapse folders'}))
 expect(screen.queryByRole('separator')).toBeNull()
 expect(JSON.parse(localStorage.getItem('jpack.pack-folders.view.v1:/project')!).collapsed).toBe(true)
 expect(screen.getByRole('button',{name:'Expand folders'}).closest('[data-page-header]')).not.toBeNull()
 expect(within(screen.getByRole('navigation',{name:'Folder location'})).queryByRole('button',{name:'Expand folders'})).toBeNull()
 fireEvent.click(screen.getByRole('button',{name:'Expand folders'}))
 expect(screen.getByRole('separator').getAttribute('aria-valuenow')).toBe('228')
})
it('uses a closable drawer in narrow panes without changing the desktop preference',async()=>{
 setup({width:620});await screen.findByRole('link',{name:/home-pack/})
 const show=screen.getByRole('button',{name:'Expand folders'});show.focus();fireEvent.click(show)
 const drawer=screen.getByRole('dialog',{name:'Folders'})
 fireEvent.click(within(drawer).getByRole('button',{name:'Collapse folders'}))
 await waitFor(()=>expect(screen.queryByRole('dialog')).toBeNull())
 expect(document.activeElement).toBe(show)
 expect(JSON.parse(localStorage.getItem('jpack.pack-folders.view.v1:/project')!).collapsed).toBe(false)
})
it('shows all packs and disables mutations when folder metadata cannot be read',async()=>{
 setup({corrupt:true})
 await screen.findByText(/Folder organization is unavailable/)
 fireEvent.keyDown(screen.getByRole('button',{name:'Collection options'}),{key:'Enter'})
 expect((await screen.findByRole('menuitem',{name:'New folder'})).getAttribute('aria-disabled')).toBe('true')
 fireEvent.keyDown(screen.getByRole('menu'),{key:'Escape'})
 await screen.findByRole('link',{name:/department-pack/})
 expect(screen.getByRole('link',{name:/home-pack/})).toBeTruthy()
 expect(saveFolderAction).not.toHaveBeenCalled()
})
it('restores a direct pack link to its folder and expanded ancestors',async()=>{
 setup({path:'/packs/department-pack'})
 await waitFor(()=>expect(screen.getByRole('navigation',{name:'Folder location'}).textContent).toContain('Intake'))
 expect(screen.queryByRole('navigation',{name:'Folder navigation'})).toBeNull()
 fireEvent.click(screen.getByRole('button',{name:'Expand folders'}))
 const tree=screen.getByRole('navigation',{name:'Folder navigation'})
 expect(within(tree).getByRole('button',{name:'Intake'}).getAttribute('aria-current')).toBe('location')
 await act(async()=>{})
})

it('keeps the original Packs & graphs search scope when returning from a pack',async()=>{
 const {router}=setup();await screen.findByRole('link',{name:/home-pack/})
 fireEvent.click(within(screen.getByRole('navigation',{name:'Folder location'})).getByRole('button',{name:'Packs & graphs'}))
 fireEvent.change(screen.getByRole('searchbox',{name:'Search packs and graphs'}),{target:{value:'pack'}})
 fireEvent.click(await screen.findByRole('link',{name:/department-pack/}))
 await screen.findByText('Pack content')
 await act(async()=>router.navigate(-1))
 expect(screen.getByRole('searchbox',{name:'Search packs and graphs'}).getAttribute('value')).toBe('pack')
 expect(within(screen.getByRole('navigation',{name:'Folder location'})).getByRole('button',{name:'Packs & graphs'}).getAttribute('aria-current')).toBe('location')
 expect(screen.getByRole('link',{name:/home-pack/})).toBeTruthy()
})
it('preserves a typed folder name through dock and drawer transitions',async()=>{
 const {resize}=setup();await screen.findByRole('link',{name:/home-pack/})
 await newFolder()
 fireEvent.change(screen.getByRole('textbox',{name:'Folder name'}),{target:{value:'Unfinished department'}})
 resize(620)
 expect(within(screen.getByRole('dialog')).getByRole('textbox',{name:'Folder name'}).getAttribute('value')).toBe('Unfinished department')
 resize(1100)
 expect(screen.getByRole('dialog',{name:'New folder'})).toBeTruthy()
 expect(screen.getByRole('textbox',{name:'Folder name'}).getAttribute('value')).toBe('Unfinished department')
})
it('restores drawer focus after cancelling an inner folder editor',async()=>{
 setup({width:620});await screen.findByRole('link',{name:/home-pack/})
 const show=screen.getByRole('button',{name:'Expand folders'});show.focus();fireEvent.click(show)
 fireEvent.click(screen.getByRole('button',{name:'New workspace folder'}))
 expect(screen.queryByRole('dialog',{name:'Folders'})).toBeNull()
 fireEvent.click(screen.getByRole('button',{name:'Cancel'}))
 await waitFor(()=>expect(document.activeElement).toBe(show))
})
it('does not remount an open document when the project root arrives late',async()=>{
 const {client}=setup({path:'/packs/home-pack',rootPending:true})
 const input=await screen.findByRole('textbox',{name:'Unfinished edit'})
 fireEvent.change(input,{target:{value:'Unsaved policy'}})
 act(()=>client.setQueryData(['desk-files'],{root:'/resolved-project',files:[]}))
 expect(screen.getByRole('textbox',{name:'Unfinished edit'})).toBe(input)
 expect(input.getAttribute('value')).toBe('Unsaved policy')
})

it('does not redirect a newer navigation when an assignment retry finishes',async()=>{
 let resolve!:(value:Awaited<ReturnType<typeof assignCreatedPack>>)=>void
 vi.mocked(assignCreatedPack).mockReturnValue(new Promise(done=>{resolve=done}))
 const {router}=setup({path:'/packs/department-pack',state:{folderAssignment:{packId:'department-pack',folderId:'child'}}})
 fireEvent.click(await screen.findByRole('button',{name:'Retry folder assignment'}))
 await act(async()=>router.navigate('/packs/home-pack'))
 await act(async()=>resolve({document:defaultFolders(),digest:'saved'}))
 expect(router.state.location.pathname).toBe('/packs/home-pack')
})

it('keeps the editor base digest through background refreshes and adopts a new base only on explicit reload',async()=>{
 const {client}=setup();await screen.findByRole('link',{name:/home-pack/})
 await newFolder()
 fireEvent.change(screen.getByRole('textbox',{name:'Folder name'}),{target:{value:'Unsaved folder'}})
 const before=client.getQueryData<{document:ReturnType<typeof defaultFolders>;digest:string}>(FOLDERS_KEY)!
 act(()=>client.setQueryData(FOLDERS_KEY,{...before,digest:'background-refresh'}))
 vi.mocked(saveFolderAction).mockRejectedValueOnce(new Error('Folders changed in another window. Reload folders and try again.'))
 fireEvent.click(screen.getByRole('button',{name:'Create folder'}))
 await screen.findByText(/Folders changed in another window/)
 expect(vi.mocked(saveFolderAction).mock.calls[0]![0].digest).toBe('read')
 vi.mocked(loadFolders).mockResolvedValueOnce({...before,digest:'explicit-reload'})
 fireEvent.click(screen.getByRole('button',{name:'Reload folders'}))
 await waitFor(()=>expect(client.getQueryData<{digest:string}>(FOLDERS_KEY)?.digest).toBe('explicit-reload'))
 expect(screen.getByRole('textbox',{name:'Folder name'}).getAttribute('value')).toBe('Unsaved folder')
 fireEvent.click(screen.getByRole('button',{name:'Create folder'}))
 await waitFor(()=>expect(saveFolderAction).toHaveBeenCalledTimes(2))
 expect(vi.mocked(saveFolderAction).mock.calls[1]![0].digest).toBe('explicit-reload')
})

it('keeps the current folder visible and makes collapsed ancestors navigable',async()=>{
 const {router,resize}=setup({path:'/packs/department-pack'})
 const location=await screen.findByRole('navigation',{name:'Folder location'})
 await waitFor(()=>expect(within(location).getByRole('button',{name:'Intake'}).getAttribute('aria-current')).toBe('location'))
 expect(within(location).getByRole('button',{name:'Operations'})).toBeTruthy()
 resize(420)
 expect(within(location).queryByRole('button',{name:'Operations'})).toBeNull()
 expect(within(location).getByRole('button',{name:'Intake'}).getAttribute('aria-current')).toBe('location')
 fireEvent.keyDown(within(location).getByRole('button',{name:'Show parent folders'}),{key:'Enter'})
 const menu=await screen.findByRole('menu')
 fireEvent.click(within(menu).getByRole('menuitem',{name:/Operations/}))
 await waitFor(()=>expect(router.state.location.pathname).toBe('/packs'))
 expect(within(screen.getByRole('navigation',{name:'Folder location'})).getByRole('button',{name:'Operations'}).getAttribute('aria-current')).toBe('location')
 expect(saveFolderAction).not.toHaveBeenCalled()
})

it('restores focus when dismissing the parent folder menu without changing location',async()=>{
 const {router}=setup({path:'/packs/department-pack'})
 const location=await screen.findByRole('navigation',{name:'Folder location'})
 const trigger=await within(location).findByRole('button',{name:'Show parent folders'})
 trigger.focus()
 fireEvent.keyDown(trigger,{key:'Enter'})
 const menu=await screen.findByRole('menu')
 expect(within(menu).getByRole('menuitem',{name:/local.user@example.com/})).toBeTruthy()
 fireEvent.keyDown(menu,{key:'Escape'})
 await waitFor(()=>expect(screen.queryByRole('menu')).toBeNull())
 await waitFor(()=>expect(document.activeElement).toBe(trigger))
 expect(router.state.location.pathname).toBe('/packs/department-pack')
})

it('moves a graph with its own folder identity and a readable label',async()=>{
 const {client}=setup({graphs:true})
 fireEvent.keyDown(await screen.findByRole('button',{name:'Options for flow'}),{key:'Enter'})
 fireEvent.click(await screen.findByRole('menuitem',{name:'Move to folder…'}))
 expect(screen.getByRole('dialog',{name:'Move graph'})).toBeTruthy()
 fireEvent.keyDown(screen.getByRole('combobox',{name:'Destination folder'}),{key:'Enter'})
 fireEvent.click(await screen.findByRole('option',{name:/Operations$/}))
 fireEvent.click(within(screen.getByRole('dialog',{name:'Move graph'})).getByRole('button',{name:'Move'}))
 await waitFor(()=>expect(saveFolderAction).toHaveBeenCalled())
 const doc=client.getQueryData<{document:{version:number;assignments:Record<string,string>}}>(FOLDERS_KEY)!.document
 expect(doc.version).toBe(2);expect(doc.assignments['graph:flow']).toBe('dept');expect(doc.assignments['department-pack']).toBe('child')
})

it('keeps only actual folders in the left tree and returns to all items through the location bar',async()=>{
 setup();await screen.findByRole('link',{name:/home-pack/})
 expect(within(screen.getByRole('navigation',{name:'Folder navigation'})).queryByRole('button',{name:'Packs & graphs'})).toBeNull()
 fireEvent.click(within(screen.getByRole('navigation',{name:'Folder location'})).getByRole('button',{name:'Packs & graphs'}))
 expect(await screen.findByRole('link',{name:/department-pack/})).toBeTruthy()
})

it('moves selected packs and graphs together in one conflict-checked folder write',async()=>{
 const {client}=setup({graphs:true});await screen.findByRole('link',{name:/home-pack/})
 fireEvent.click(await screen.findByRole('checkbox',{name:'Select flow'}))
 fireEvent.click(screen.getByRole('checkbox',{name:'Select home-pack'}))
 fireEvent.click(screen.getByRole('button',{name:'Move to…'}))
 const dialog=screen.getByRole('dialog',{name:'Move selected items'})
 fireEvent.keyDown(within(dialog).getByRole('combobox',{name:'Destination folder'}),{key:'Enter'})
 fireEvent.click(await screen.findByRole('option',{name:/Operations$/}))
 fireEvent.click(within(dialog).getByRole('button',{name:'Move'}))
 await waitFor(()=>expect(saveFolderAction).toHaveBeenCalledOnce())
 expect(vi.mocked(saveFolderAction).mock.calls[0]![0].digest).toBe('read')
 const doc=client.getQueryData<{document:{assignments:Record<string,string>}}>(FOLDERS_KEY)!.document
 expect(doc.assignments['graph:flow']).toBe('dept');expect(doc.assignments['home-pack']).toBe('dept')
 expect(doc.assignments['department-pack']).toBe('child')
})
