/** Shared tooltip and pack-list browser checks. Requires the development design-system
 * page and a disposable inventory with pack-000 (clipped question) and pack-001
 * (question longer than 320 characters). Does not write project data.
 * Usage: node scripts/tooltip-check.mjs <design-system-url> <fixture-launch-log> <artifact-dir>
 */
import { createRequire } from 'node:module'
import { readFile, writeFile, mkdir } from 'node:fs/promises'
const { chromium } = createRequire(new URL('../web/package.json', import.meta.url))('playwright-core')
const [designURL, fixtureLog, artifactDir] = process.argv.slice(2)
if (!designURL || !fixtureLog || !artifactDir) throw new Error('Expected design page URL, fixture log and artifact directory')
await mkdir(artifactDir, { recursive: true })
const launch = (await readFile(fixtureLog, 'utf8')).match(/http:\/\/[^\s]+\/launch\?secret=[^\s]+/)?.[0]
if (!launch) throw new Error('Fixture launch URL unavailable')
const origin = new URL(launch).origin, secret = new URL(launch).searchParams.get('secret')
const browser = await chromium.launch({executablePath:process.env.PLAYWRIGHT_CHROME,args:['--no-sandbox']})
const checks=[];const errors=[]
const page=await browser.newPage({viewport:{width:1102,height:850},colorScheme:'dark'})
page.on('pageerror',e=>errors.push(e.message.replaceAll(secret, '[redacted]')))
const check=(name,pass)=>{checks.push({name,pass});if(!pass)throw new Error(name)}
try{
 await page.goto(designURL)
 const icon=page.getByRole('button',{name:'Example Inspector',exact:true})
 await icon.hover(); await page.getByRole('tooltip').waitFor()
 check('hover opens compact hint',await page.getByRole('tooltip').innerText()==='Open InspectorMod+Alt+I')
 check('existing accessible description retained',(await icon.getAttribute('aria-describedby')).includes('tooltip-existing-help'))
 const bubble=page.locator('[data-radix-popper-content-wrapper]').filter({has:page.getByRole('tooltip')})
 await bubble.hover();await page.waitForTimeout(400);check('bubble remains hoverable',await page.getByRole('tooltip').isVisible())
 await page.keyboard.press('Escape');check('Escape dismisses',await page.getByRole('tooltip').count()===0)
 await page.getByRole('button',{name:'Fits',exact:true}).hover();await page.waitForTimeout(450);check('fitting label has no tooltip',await page.getByRole('tooltip').count()===0)
 const clipped=page.getByRole('button',{name:'A longer question that cannot fit in a compact collection row'})
 await clipped.hover();await page.getByRole('tooltip').waitFor();check('clipped text revealed',await page.getByRole('tooltip').innerText()==='A longer question that cannot fit in a compact collection row')
 await clipped.evaluate(el=>el.style.maxWidth='100%');await page.waitForTimeout(100);check('resize to fit dismisses hint',await page.getByRole('tooltip').count()===0)
 await icon.focus();await page.getByRole('tooltip').waitFor();check('keyboard focus opens',true);await page.keyboard.press('Escape');check('focus stays on trigger',await icon.evaluate(el=>el===document.activeElement))
 await page.getByRole('button',{name:'Open tooltip dialog'}).click()
 const dialog=page.getByRole('dialog',{name:'Tooltips inside a dialog',exact:true})
 await dialog.getByRole('button',{name:'Example dialog action'}).hover();await page.getByRole('tooltip').waitFor()
 check('dialog hint above modal',await page.getByRole('tooltip').evaluate(el=>{const p=el.closest('[data-radix-popper-content-wrapper]');return Number(getComputedStyle(p).zIndex)>=70}))
 await page.keyboard.press('Escape');check('Escape closes tooltip before dialog',await dialog.isVisible())
 await dialog.getByRole('button',{name:/Show full digest/}).click()
 const digest=page.getByRole('dialog',{name:'Full digest'});await digest.waitFor()
 check('digest selectable in modal',await digest.locator('code').innerText()==='abcdef0123456789'.repeat(4))
 await page.screenshot({path:`${artifactDir}/modal.png`})
 await page.keyboard.press('Escape');await page.getByRole('button',{name:'Close example dialog'}).click()
 for(const width of [390,768,1440]){await page.setViewportSize({width,height:850});await icon.hover();await page.getByRole('tooltip').waitFor();check(`tooltip fits ${width}`,await page.getByRole('tooltip').evaluate(el=>{const r=el.parentElement.getBoundingClientRect();return r.left>=0&&r.right<=innerWidth&&r.top>=0&&r.bottom<=innerHeight}));await page.keyboard.press('Escape')}
 const touch=await browser.newPage({hasTouch:true,viewport:{width:390,height:844},isMobile:true})
 await touch.goto(designURL);await touch.getByRole('button',{name:'Example Inspector',exact:true}).tap();await touch.waitForTimeout(450);check('touch does not leave tooltip',await touch.getByRole('tooltip').count()===0);await touch.close()

 for (const theme of ['dark', 'light']) for (const density of ['comfortable', 'compact']) {
  const p = await browser.newPage({viewport:{width:1440,height:900},colorScheme:theme})
  p.on('pageerror', e => errors.push(e.message.replaceAll(secret, '[redacted]')))
  await p.goto(launch); await p.locator('.desk').waitFor(); await p.goto(origin + '/packs'); await p.locator('[data-pack-list] a').first().waitFor()
  await p.evaluate(value => document.documentElement.dataset.density = value, density)
  const row=p.locator('[data-pack-list] a[href="/packs/pack-000"]')
  await row.scrollIntoViewIfNeeded(); await row.hover(); await p.getByRole('tooltip').waitFor()
  const question=await row.locator('[data-overflow-text]').nth(1).innerText()
  check(`${theme}/${density}: full clipped question`,await p.getByRole('tooltip').innerText()===question)
  const geometry=await row.evaluate(el=>({height:el.getBoundingClientRect().height,width:el.clientWidth,scroll:el.scrollWidth}))
  check(`${theme}/${density}: row stays compact`,geometry.height<=40 && geometry.scroll<=geometry.width+1)
  check(`${theme}/${density}: no native browser hints`,await p.locator('[title]:not(svg title)').count()===0)
  await p.getByRole('button',{name:'Preview pack-000',exact:true}).click()
  check(`${theme}/${density}: preview dismisses hint`,await p.getByRole('tooltip').count()===0)
  const preview=p.getByRole('region',{name:'Pack preview',exact:true})
  check(`${theme}/${density}: preview shows whole question`,(await preview.innerText()).includes(question))
  await row.hover();await p.getByRole('tooltip').waitFor()
  const separator=p.getByRole('separator',{name:'Inspector',exact:true})
  const bounds=await separator.boundingBox();await p.mouse.move(bounds.x+bounds.width/2,bounds.y+120);await p.mouse.down();await p.mouse.move(bounds.x-90,bounds.y+120,{steps:6});await p.mouse.up();await p.mouse.move(10,10)
  check(`${theme}/${density}: dragging leaves no hint`,await p.getByRole('tooltip').count()===0)
  check(`${theme}/${density}: no residual divider paint`,await separator.evaluate(el=>getComputedStyle(el,'::after').backgroundColor==='rgba(0, 0, 0, 0)'&&!el.hasAttribute('data-dragging')))
  const huge=p.locator('[data-pack-list] a[href="/packs/pack-001"]')
  await huge.hover();await p.getByRole('tooltip').waitFor()
  check(`${theme}/${density}: huge question stays out of tooltip`,await p.getByRole('tooltip').innerText()==='Open Preview to read the full pack details.')
  await p.getByRole('button',{name:'Preview pack-001',exact:true}).click()
  check(`${theme}/${density}: huge question available in Preview`,(await preview.innerText()).length>320)
  await p.screenshot({path:`${artifactDir}/${theme}-${density}.png`})
  await huge.hover();await p.getByRole('tooltip').waitFor()
  await p.locator('[data-pack-list]').evaluate(el=>el.scrollTop=el.scrollHeight)
  await p.waitForTimeout(150)
  check(`${theme}/${density}: virtualized scrolling dismisses`,await p.getByRole('tooltip').count()===0)
  check(`${theme}/${density}: collection remains virtualized`,await p.locator('[data-pack-list] a').count()<100)
  await p.close()
 }
 const mobile=await browser.newPage({viewport:{width:390,height:844},isMobile:true,hasTouch:true,colorScheme:'dark'})
 await mobile.goto(launch);await mobile.locator('.desk').waitFor();await mobile.goto(origin + '/packs');await mobile.locator('[data-pack-list] a').first().waitFor()
 await mobile.getByRole('button',{name:'Preview pack-000',exact:true}).tap()
 check('mobile preview reads question without hover',(await mobile.getByRole('region',{name:'Pack preview'}).innerText()).includes('May this investigation'))
 check('mobile preview does not leave tooltip',await mobile.getByRole('tooltip').count()===0)
 check('mobile has no horizontal overflow',await mobile.evaluate(()=>document.documentElement.scrollWidth<=innerWidth))
 await mobile.screenshot({path:`${artifactDir}/mobile-preview.png`})
 await mobile.close()
}catch(e){errors.push(e.message.replaceAll(secret, '[redacted]'))}finally{await browser.close();await writeFile(`${artifactDir}/results.json`,JSON.stringify({checks,errors},null,2));console.log(JSON.stringify({checks,errors},null,2));if(errors.length)process.exitCode=1}
