/** Isolated design preview. Fictional cases, evidence, checks, reviews and runs.
 * The pack title and three requirements reflect the retained 0.1.0 pack.
 * No API, AI, authentication or persistence. Not imported by the production app.
 * English copy is for review; production implementation must use localization. */
import { useEffect, useRef, useState, type ReactNode } from 'react'
import { createRoot } from 'react-dom/client'
import { Button } from '../ui/Button'
import { Disclosure } from '../ui/Disclosure'
import { Select } from '../ui/Select'
import { Popover, PopoverClose } from '../ui/Popover'
import { TextArea } from '../ui/TextArea'
import { Tooltip, TooltipProvider } from '../ui/Tooltip'
import { IconActivity, IconAssistant, IconCheck, IconChevronDown, IconChevronLeft, IconChevronRight, IconClose, IconDetails, IconFocus, IconMore, IconGear, IconGraph, IconHelp, IconHistory, IconPack, IconPanelLeft } from '../shell/icons'
import '../styles.css'
import styles from './EvidenceBriefDesign.module.css'

type Screen = 'case' | 'job' | 'run' | 'changed' | 'empty'
type Pane = 'brief' | 'source' | 'history' | 'details' | 'assistant' | 'activity' | null
const screens: { id: Screen; label: string }[] = [
  { id: 'case', label: 'Test case' }, { id: 'job', label: 'Job setup' }, { id: 'run', label: 'Operational run' },
  { id: 'changed', label: 'Inputs changed' }, { id: 'empty', label: 'Before generation' }
]
function query() { return new URLSearchParams(location.hash.slice(1)) }
function readScreen(): Screen { const value = query().get('screen'); return screens.some(s => s.id === value) ? value as Screen : 'case' }
function readPane(): Pane { const value = query().get('pane'); return value === 'closed' ? null : value === 'source' || value === 'history' ? value : 'brief' }
function Tag({ children, tone = 'neutral' }: { children: ReactNode; tone?: 'neutral' | 'good' | 'warn' }) { return <span className={styles.tag} data-tone={tone}>{children}</span> }
function IconButton({ label, children, onClick, active = false }: { label: string; children: ReactNode; onClick: () => void; active?: boolean }) {
  return <Tooltip content={label}><Button variant="quiet" size="icon" aria-label={label} aria-pressed={active || undefined} onClick={() => { document.dispatchEvent(new Event('desk-tooltip-dismiss')); onClick() }}>{children}</Button></Tooltip>
}
function Section({ title, children, aside }: { title: string; children: ReactNode; aside?: ReactNode }) { return <section className={styles.section}><div className={styles.sectionTitle}><h2>{title}</h2>{aside}</div>{children}</section> }
/** Proposed Brief glyph follows the existing 16px, 1.75px outline vocabulary. */
function IconBrief() { return <svg width="16" height="16" viewBox="0 0 16 16" fill="none" stroke="currentColor" strokeWidth="1.75" strokeLinecap="round" strokeLinejoin="round" aria-hidden="true" focusable="false"><path d="M8 3.5C6.5 2.2 4 2 1.5 2.5v10C4 12 6.5 12.2 8 13.5c1.5-1.3 4-1.5 6.5-1v-10C12 2 9.5 2.2 8 3.5Zm0 0v10" /></svg> }
const paneNames: Record<Exclude<Pane, null>, string> = { brief: 'Brief', source: 'Source', history: 'Brief history', details: 'Details', assistant: 'Assistant', activity: 'Activity' }
function App() {
  const [screen, setScreen] = useState<Screen>(readScreen)
  const [pane, setPane] = useState<Pane>(readPane)
  const [expanded, setExpanded] = useState(query().get('expanded') === '1')
  const [source, setSource] = useState('scope')
  const [theme, setTheme] = useState('dark')
  const [collapsed, setCollapsed] = useState(false)
  const [revision, setRevision] = useState(2)
  const [chatDraft, setChatDraft] = useState('')
  const [notice, setNotice] = useState('Static design preview · Fictional cases, runs and evidence. Nothing is generated or saved.')
  const briefScroll = useRef<HTMLDivElement>(null)
  const rail = useRef<HTMLElement>(null)
  const isCase = screen === 'case' || screen === 'empty'
  const isJob = screen === 'job'
  const subject = isCase ? 'Missing privacy scan' : isJob ? 'Contribution intake review' : 'Policy evidence playbook'
  const preview = (message: string) => setNotice(`Preview only: ${message}`)
  useEffect(() => {
    const change = () => { setScreen(readScreen()); setPane(readPane()); setExpanded(query().get('expanded') === '1'); setSource('scope'); setRevision(2); setNotice('Static design preview · Fictional cases, runs and evidence. Nothing is generated or saved.'); briefScroll.current?.scrollTo(0, 0) }
    addEventListener('hashchange', change); return () => removeEventListener('hashchange', change)
  }, [])
  useEffect(() => { document.documentElement.dataset.theme = theme }, [theme])
  function closePane() { const previous = pane; setPane(null); requestAnimationFrame(() => rail.current?.querySelector<HTMLButtonElement>(`button[aria-label="${previous === 'source' || previous === 'history' ? 'Brief' : previous ? paneNames[previous] : 'Brief'}"]`)?.focus()) }
  function restore() { setExpanded(false) }
  useEffect(() => { if (!pane) return; const close = (event: KeyboardEvent) => { if (event.key !== 'Escape') return; if (pane === 'source' || pane === 'history') setPane('brief'); else if (expanded) restore(); else closePane() }; addEventListener('keydown', close); return () => removeEventListener('keydown', close) }, [pane, expanded])
  function openSource(id: string) { setSource(id); setPane('source') }
  return <TooltipProvider><div className={styles.design}>
    <div className={styles.previewBar}><strong>Brief on the rail · Mock</strong><nav aria-label="Preview screens">{screens.filter(s => s.id !== 'changed').map(s => <a href={`#screen=${s.id}`} key={s.id} aria-current={screen === s.id && !expanded ? 'page' : undefined}>{s.label}</a>)}<a href="#screen=case&expanded=1" aria-current={expanded ? 'page' : undefined}>Expanded reading</a></nav><div className={styles.theme}><label htmlFor="brief-theme">Appearance</label><Select id="brief-theme" value={theme} onValueChange={setTheme} options={[{ value: 'dark', label: 'Dark' }, { value: 'light', label: 'Light' }]} /></div></div>
    <header className={styles.appHeader}><IconButton label={collapsed ? 'Expand navigation' : 'Collapse navigation'} onClick={() => setCollapsed(!collapsed)}><IconPanelLeft /></IconButton><span className={styles.brand}><span>U</span>Unveil</span><span className={styles.workspace}>Example workspace <IconChevronDown /></span><span className={styles.account}>Local owner</span></header>
    <div className={styles.body} data-collapsed={collapsed}>
      <aside className={styles.nav}><nav aria-label="Main navigation">{[{ name: 'Packs', icon: <IconPack /> }, { name: 'Graphs', icon: <IconGraph /> }, { name: 'Jobs', icon: <IconHistory /> }].map(item => <Tooltip key={item.name} content={item.name} side="right"><Button variant="quiet" aria-label={item.name} aria-current={(isCase ? 'Packs' : 'Jobs') === item.name ? 'page' : undefined} onClick={() => item.name === 'Graphs' ? preview('Graphs keeps its existing page.') : location.hash = `screen=${item.name === 'Packs' ? 'case' : 'job'}`}>{item.icon}<span>{item.name}</span></Button></Tooltip>)}</nav><div className={styles.navBottom}><Button variant="quiet" aria-label="Admin" onClick={() => preview('Admin keeps its existing page.')}><IconGear /><span>Admin</span></Button><Button variant="quiet" aria-label="Help and About" onClick={() => preview('All case and run data is fictional.')}><IconHelp /><span>Help &amp; About</span></Button></div></aside>
      <div className={styles.frame} data-pane-open={!!pane} data-expanded={expanded && !!pane}>
        <main className={styles.main}>
          <header className={styles.subjectHeader}><nav className={styles.breadcrumb} aria-label="Breadcrumb"><a href={isCase ? '#screen=case' : '#screen=job'}>{isCase ? 'Packs' : 'Jobs'}</a><IconChevronRight /><span>{isCase ? 'local.user@example.com' : 'Contribution intake review'}</span>{!isCase && !isJob && <><IconChevronRight /><span>Run 1042</span></>}</nav><div><h1>{isCase ? 'lab-notes.ai Contribution Acceptance Review' : isJob ? 'Contribution intake review' : 'Policy evidence playbook'}</h1><IconButton label="More actions" onClick={() => preview('Existing subject actions stay here. Brief is available from the right rail.')}><IconMore /></IconButton></div></header>
          <nav className={styles.tabs} aria-label="Subject views">{(isCase ? ['Overview', 'Logic', 'Tests'] : isJob ? ['Overview', 'Runs'] : ['Overview', 'Inputs & sources', 'Activity']).map(tab => <Button key={tab} variant="quiet" aria-current={tab === (isCase ? 'Tests' : 'Overview') ? 'page' : undefined} onClick={() => preview(`${tab} keeps its existing subject view.`)}>{tab}</Button>)}</nav>
          <div className={styles.content}><SubjectContent isCase={isCase} isJob={isJob} preview={preview} /></div>
        </main>
        {expanded && pane && <button className={styles.expansionBackdrop} aria-label="Return to split view" onClick={restore} />}
        {pane && <aside className={styles.railPane} data-expanded={expanded} aria-label={paneNames[pane]}>
          <header className={styles.paneHeader}><div>{(pane === 'source' || pane === 'history') && <IconButton label="Back to brief" onClick={() => setPane('brief')}><IconChevronLeft /></IconButton>}<strong>{paneNames[pane]}</strong></div><div>{pane === 'brief' && <Popover title="Brief actions" size="small" variant="list" triggerTooltip="Brief actions" trigger={<Button variant="quiet" size="icon" aria-label="Brief actions"><IconMore /></Button>}><div className={styles.briefMenu}><PopoverClose><Button variant="quiet" disabled={screen === 'empty'} onClick={() => preview('Regenerate creates a new saved one-pager. No model is called by this preview.')}>Regenerate</Button></PopoverClose><PopoverClose><Button variant="quiet" disabled={screen === 'empty'} onClick={() => setPane('history')}>Revision history</Button></PopoverClose><a href={`/mockups/evidence-briefs/${isCase ? 'test-case' : isJob ? 'job-setup' : 'operational-run'}-one-page.pdf`} download>Download sample PDF</a></div></Popover>}<IconButton label={expanded ? 'Restore pane' : 'Expand pane'} onClick={() => setExpanded(!expanded)}><IconFocus /></IconButton><IconButton label="Close pane" onClick={closePane}><IconClose /></IconButton></div></header>
          <div className={styles.panePage} hidden={pane !== 'brief'} ref={briefScroll}>
            {revision === 1 && <div className={styles.changeNotice}><span>Earlier brief · Revision 1</span><Button onClick={() => setRevision(2)}>Latest</Button></div>}
            {screen === 'changed' && <div className={styles.changeNotice}><span>New evidence is available. This saved brief is unchanged.</span></div>}
            {screen === 'empty' ? <div className={styles.empty}><IconBrief /><h2>A one-page brief for this case</h2><p>Context, required evidence, findings and next steps in one readable document.</p><Button variant="primary" onClick={() => preview('Generate would save the first brief. No AI call or storage write was made.')}>Generate brief</Button><p className={styles.hint}>Generated once on request. Everyone with access reads the same saved revision.</p></div> : <article className={styles.paper} aria-label="One-page brief"><header className={styles.paperHeader}><div className={styles.paperKicker}>{isCase ? 'Test case brief' : isJob ? 'Job brief' : 'Decision brief'}<span>Sep 25, 2026</span></div><h2>{subject}</h2><p className={styles.paperContext}>{isCase ? 'Case revision 3 · Pack 0.1.0' : isJob ? 'Manual / API · Fixed release 1' : 'Run 1042 · Pack 0.1.0'}</p></header><OnePager kind={isCase ? 'case' : isJob ? 'job' : 'run'} revision={revision} openSource={openSource} /><footer className={styles.paperFooter}><span>AI-assisted · Revision {revision} · Saved 10:20 AM<br />Illustrative content · Not reviewed</span><button className={styles.textLink} onClick={() => setPane('details')}>Supporting records <IconChevronRight /></button></footer></article>}
          </div>
          <div className={styles.panePage} hidden={pane !== 'source'}><SourceReader source={source} isCase={isCase} /></div>
          <div className={styles.panePage} hidden={pane !== 'history'}><h2>Saved revisions</h2><p className={styles.hint}>Viewing a saved revision makes no AI request.</p>{[2, 1].map(rev => <button className={styles.revision} key={rev} onClick={() => { setRevision(rev); setPane('brief'); briefScroll.current?.scrollTo(0, 0) }}><strong>Revision {rev}</strong><small>Sep 25 · {rev === 2 ? '10:20' : '09:40'} AM</small><p>{rev === 2 ? 'Latest saved brief' : 'Initial brief'}</p></button>)}</div>
          <div className={styles.panePage} hidden={pane !== 'details'}><h2>{subject}</h2><dl className={styles.subjectProperties}><dt>Pack</dt><dd>Contribution Acceptance Review · 0.1.0</dd><dt>{isCase ? 'Expected result' : 'Recorded result'}</dt><dd>{isJob ? 'No particular run selected' : 'Unresolved'}</dd><dt>Required evidence</dt><dd>Automated check receipt<br />Privacy scan log<br />Source register verification</dd><dt>Source checks</dt><dd>Example files match their retained digests. Adequacy has not been reviewed.</dd></dl><Disclosure title="Technical details"><p>Pack, input and result snapshots would remain here, separate from the readable brief.</p></Disclosure></div>
          <div className={styles.panePage} hidden={pane !== 'assistant'}><h2>Ask about this {isCase ? 'case' : 'job'}</h2><p className={styles.hint}>The saved brief is available as context.</p><div className={styles.chatComposer}><label htmlFor="preview-chat">Message</label><TextArea id="preview-chat" value={chatDraft} onChange={e => setChatDraft(e.target.value)} placeholder="Ask a question…" rows={4} /><Button onClick={() => preview('No chat is sent from the mock.')}>Send</Button></div></div>
          <div className={styles.panePage} hidden={pane !== 'activity'}><h2>Recent activity</h2><p>10:20 AM · Brief revision 2 saved</p><p>10:06 AM · {isCase ? 'Test run 28 passed' : 'Run 1042 completed'}</p><p className={styles.hint}>Illustrative history only.</p></div>
        </aside>}
        <nav className={styles.toolrail} aria-label="Workspace tools" ref={rail}>{[{id:'assistant' as const,label:'Assistant',icon:<IconAssistant />},{id:'brief' as const,label:'Brief',icon:<IconBrief />},{id:'details' as const,label:'Details',icon:<IconDetails />},{id:'activity' as const,label:'Activity',icon:<IconActivity />}].map(tool => <IconButton key={tool.id} label={tool.label} active={pane === tool.id || tool.id === 'brief' && (pane === 'source' || pane === 'history')} onClick={() => pane === tool.id ? closePane() : setPane(tool.id)}>{tool.icon}</IconButton>)}</nav>
      </div>
    </div><footer className={styles.previewNote} role="status">{notice}</footer>
  </div></TooltipProvider>
}
function SubjectContent({ isCase, isJob, preview }: { isCase: boolean; isJob: boolean; preview: (message: string) => void }) {
  if (isCase) return <><div className={styles.caseToolbar}><div><Button variant="quiet" aria-pressed>Cases · 4</Button><Button variant="quiet" onClick={() => preview('Run history keeps its current view.')}>Run history</Button></div><div><Button onClick={() => preview('Case creation stays in the existing flow.')}>New case</Button><Button onClick={() => preview('Assistant designs cases through the existing flow.')}>Design with AI</Button><Button variant="primary" onClick={() => preview('No test run is started.')}>Run tests</Button></div></div><div className={styles.listTools}><span>Search cases…</span><span>All results <IconChevronDown /></span></div><div className={styles.caseTable}><table><thead><tr><th>Case</th><th>Expected</th><th>Last result</th></tr></thead><tbody>{[['Clean playbook contribution','Accept'],['Personal data detected','Reject'],['Missing privacy scan','Unresolved'],['Unknown automated check result','Unresolved']].map(([name,result]) => <tr key={name} aria-selected={name === 'Missing privacy scan'} onClick={() => preview('This static example keeps Missing privacy scan selected.')}><td>{name}</td><td>{result}</td><td className={styles.passed}>Passed</td></tr>)}</tbody></table></div><p className={styles.hint}>4 cases · Pack version 0.1.0</p></>
  return <div className={styles.subjectOverview}><Section title={isJob ? 'About this job' : 'Run result'}><p>{isJob ? 'Review contributions against the repository’s privacy, traceability and automated-check requirements.' : 'Evaluation completed. The contribution remains unresolved because its required privacy scan was not supplied.'}</p></Section><dl className={styles.subjectProperties}><dt>{isJob ? 'Trigger' : 'Execution'}</dt><dd>{isJob ? 'Manual / API' : 'Completed'}</dd><dt>{isJob ? 'Owner' : 'Pack decision'}</dt><dd>{isJob ? 'Local owner' : 'Unresolved'}</dd><dt>Policy</dt><dd>Contribution Acceptance Review · Fixed release 1</dd><dt>{isJob ? 'Latest run' : 'Requested handoff'}</dt><dd>{isJob ? 'Run 1042 · Completed · Unresolved' : 'Repository Maintainer'}</dd></dl><Section title={isJob ? 'Recent runs' : 'Evidence received'}>{isJob ? <a href="#screen=run">Run 1042 · Policy evidence playbook</a> : <><p>Automated check receipt · Provided</p><p className={styles.warning}>Privacy scan log · Missing</p><p>Source register verification · Provided</p></>}</Section></div>
}
function OnePager({ kind, revision, openSource }: { kind: 'case' | 'job' | 'run'; revision: number; openSource: (id: string) => void }) {
  const isCase = kind === 'case', isJob = kind === 'job'
  return <div className={styles.paperBody}>
    <p className={styles.summary}>{isCase ? 'Check that missing privacy evidence keeps a contribution unresolved, even when the submitted facts report no personal data.' : isJob ? 'Apply the repository’s contribution policy consistently, with the evidence needed to understand each result and follow up on gaps.' : 'The contribution remains unresolved because the required privacy scan is missing. A separate objection about the proposed rollout also needs human assessment.'}</p>
    <section><h2>{isCase ? 'Scenario' : isJob ? 'Scope & operation' : 'Context'}</h2><p>{isCase ? 'A playbook contribution reports successful automated checks, traceable claims and accessible sources. Its privacy scan log is deliberately omitted. This isolates the pack’s handling of missing required evidence.' : isJob ? 'Evaluate one playbook, dataset, skill, source update or domain brief per submission. The local owner starts a run manually or through the API. Each run uses the fixed Contribution Acceptance Review release.' : 'The submitted playbook describes a consultation evidence workflow using synthetic records. The question is whether it may enter the repository; this pack does not determine consultation consensus or authorize a rollout.'}</p></section>
    <section><h2>{isJob ? 'Evidence required for every submission' : 'Required evidence'}</h2><ul className={styles.evidenceList}>
      <li><span>{isJob ? <strong>Automated check receipt</strong> : <button className={styles.textLink} onClick={() => openSource('checks')}>Automated check receipt</button>} — record of content tests and skill validation.</span><span>{isJob ? 'Required' : 'Provided'}</span></li>
      <li><span><strong>Privacy scan log</strong> — check for person-level data in submitted records.</span><span className={isJob ? undefined : styles.warning}>{isJob ? 'Required' : 'Missing'}</span></li>
      <li><span>{isJob ? <strong>Source register verification</strong> : <button className={styles.textLink} onClick={() => openSource('register')}>Source register verification</button>} — registered sources and access conditions.</span><span>{isJob ? 'Required' : 'Provided'}</span></li>
    </ul><p className={styles.paperNote}>{isJob ? 'Each run needs its own evidence. An availability declaration does not attach a document.' : 'The supplied files have not been assessed for adequacy. Their presence alone does not establish that the contribution is acceptable.'}</p></section>
    <section><h2>{isCase ? 'Expected & observed result' : isJob ? 'How results are handled' : 'Findings & uncertainty'}</h2><p>{isCase ? 'Expected: unresolved, with a Repository Maintainer handoff. Test run 28 produced that result, so the case passed. This confirms the saved expectation; it does not approve the contribution.' : isJob ? 'Record acceptance, rejection or an unresolved result. Preserve any requested maintainer handoff. A request for review is not a completed review; this job does not send an external approval or message.' : revision === 1 ? 'Evaluation completed and requested maintainer review for the missing privacy scan. The evidence does not yet support a contribution decision.' : <>Evaluation completed and requested maintainer review. A <button className={styles.textLink} onClick={() => openSource('scope')}>retained scope note</button> says, “The source register covers the pilot, but not the expanded rollout.” Its relevance remains unresolved.</>}</p></section>
    <section><h2>{isCase ? 'Limits & open questions' : isJob ? 'Readiness gaps' : 'Human review'}</h2><p>{isCase ? 'This case does not establish the source material’s meaning or resolve objections to the playbook. The evidence assumptions still need reviewer assessment before the case supports a release.' : isJob ? 'No saved behavioral test run is linked to this release. Source artifact bindings need setup, and no readiness review is recorded. Structural validation alone does not establish policy suitability.' : 'A reviewer confirmed the underlying interpretation’s wording. That review does not settle the scope objection or approve the contribution. No human contribution decision is recorded.'}</p></section>
    <section className={styles.nextStep}><h2>{isCase ? 'Next step' : isJob ? 'Before regular use' : 'Next decision'}</h2><p>{isCase ? 'Have the test owner review the assumptions, then add a companion case with the privacy scan supplied to check the acceptance path.' : isJob ? 'The owner should bind the source artifacts, attach a test run for the exact release and arrange a readiness review before relying on this job for recurring work.' : 'Ask the contributor for the privacy scan and the maintainer to assess the scope objection. Evaluate the new evidence in a linked run; keep this result and brief unchanged.'}</p></section>
  </div>
}
function SourceReader({ source, isCase }: { source: string; isCase: boolean }) {
  const scope = source === 'scope', checks = source === 'checks'
  return <><span className={styles.eyebrow}>Retained source · Synthetic example</span><h2>{scope ? 'Scope review note' : checks ? 'Automated check receipt' : 'Source register verification'}</h2><p className={styles.hint}>Saved with {isCase ? 'case revision 3' : 'run 1042'} · Sep 25, 09:58 AM</p><div className={styles.sourceBody}><span>{scope ? 'Reviewer note · Paragraph 2' : checks ? 'Check report · Summary' : 'Source register · Summary'}</span><blockquote>{scope ? 'The source register covers the pilot, but not the expanded rollout.' : checks ? 'Content tests and skill validation completed successfully for the submitted revision.' : 'The listed public sources resolved when the register was checked. Access conditions are recorded for each entry.'}</blockquote></div><Section title="What was checked"><div className={styles.checkRow}><IconCheck /><span>{scope ? 'Quote matches this saved note' : 'File matches its retained digest'}</span></div><p className={styles.hint}>{scope ? 'This checks the text and its location. It does not settle the objection.' : 'This confirms file identity. It does not establish the report’s truth or the adequacy of the evidence.'}</p></Section><Section title="Human assessment"><Tag tone="warn">{scope ? 'Not resolved' : 'Not reviewed'}</Tag><p>{scope ? 'No recorded assessment of whether the pilot evidence supports the wider rollout.' : 'No assessment of this artifact’s adequacy for this contribution is recorded.'}</p></Section><Disclosure title="Source details"><dl><dt>Version</dt><dd>Retained example snapshot</dd><dt>Check provenance</dt><dd>Illustrative only; no verification was performed by this preview.</dd><dt>Relationship</dt><dd>{scope ? 'Qualifies the submitted interpretation' : 'Bound to a required evidence item'}</dd></dl></Disclosure></>
}
createRoot(document.getElementById('root')!).render(<App />)
