package desk

import (
	"io/fs"
	"path"
)

// Project Files edits authored inputs. Runtime lockfiles and audit output have
// dedicated writers and remain inspectable without accepting arbitrary saves.
type fileAccessPolicy struct {
	auditDir string
	// auditDirUnknown is true when jpack.json is there but could not be read
	// or decoded now, so where the runtime writes its records is not known.
	// Every file with a record's name is then held read-only, wherever it is:
	// a read that failed is never taken to mean that no directory is declared.
	auditDirUnknown bool
}

func (s *Server) fileAccessPolicy() fileAccessPolicy {
	dir, declared, err := s.projectAuditDir()
	if err != nil {
		if codeOf(err) == CodeNotFound {
			return fileAccessPolicy{}
		}
		return fileAccessPolicy{auditDirUnknown: true}
	}
	policy := fileAccessPolicy{}
	if declared {
		if _, err := auditDirParts(dir); err == nil {
			policy.auditDir = path.Clean(dir)
		}
	}
	return policy
}

func (p fileAccessPolicy) readOnlyReason(name string, info fs.FileInfo) string {
	if name == runtimeLockName {
		return "runtime-lock"
	}
	switch path.Base(name) {
	case "evaluations.jsonl", "signatures.jsonl", "stamps.jsonl":
		dir := path.Dir(name)
		if p.auditDirUnknown || dir == "audit" || dir == ".desk-private/audit" || p.auditDir != "" && dir == p.auditDir {
			return "audit-record"
		}
	}
	if info != nil && info.Mode().Perm()&0o222 == 0 {
		return "file-permissions"
	}
	return ""
}

func readOnlyFileMessage(reason string) string {
	switch reason {
	case "runtime-lock":
		return "This lockfile is generated by the runtime. Update it through the pack review and lock workflow."
	case "audit-record":
		return "Audit records are generated by the runtime and cannot be edited in Project files."
	default:
		return "This file is read-only on disk. Change its filesystem permissions before editing it."
	}
}
