package desk

import (
	"io/fs"
	"os"
	"path"
	"strings"
)

// Project Files edits authored inputs. Runtime lockfiles and audit output have
// dedicated writers and remain inspectable without accepting arbitrary saves.
//
// **Names are compared without case, and files by identity.** On a
// case-insensitive filesystem (APFS, NTFS) `AUDIT/Evaluations.JSONL` and
// `JPACK.LOCK.JSON` are the record and the lock, and a declared directory
// `Records` is the folder `records`: a comparison by spelling would let either
// be replaced as an ordinary file. So the lock's name, the record names, the
// default audit directories and the declared one are compared with
// `strings.EqualFold`, as `isExcludedName` compares `.git`; and a file that
// exists is also compared, with `os.SameFile`, against the lock and the records
// at their canonical paths, which holds whatever spelling (case, Unicode
// normalization, a hard link) reaches them.
type fileAccessPolicy struct {
	auditDir string
	// auditDirUnknown is true when jpack.json is there but could not be read
	// or decoded now, so where the runtime writes its records is not known.
	// Every file with a record's name is then held read-only, wherever it is:
	// a read that failed is never taken to mean that no directory is declared.
	auditDirUnknown bool
	// canonical is what is at the lock's and the records' own paths now, each
	// with the reason a file that is the same file is read-only.
	canonical []canonicalFile
}

type canonicalFile struct {
	info   fs.FileInfo
	reason string
}

// auditRecordNames are the files the runtime writes in an audit directory.
var auditRecordNames = []string{"evaluations.jsonl", "signatures.jsonl", "stamps.jsonl"}

// defaultAuditDirs are held whatever jpack.json declares.
var defaultAuditDirs = []string{"audit", ".desk-private/audit"}

func (s *Server) fileAccessPolicy() fileAccessPolicy {
	policy := fileAccessPolicy{}
	dir, declared, err := s.projectAuditDir()
	switch {
	case err != nil && codeOf(err) != CodeNotFound:
		policy.auditDirUnknown = true
	case err == nil && declared:
		if _, err := auditDirParts(dir); err == nil {
			policy.auditDir = path.Clean(dir)
		}
	}
	policy.canonical = s.canonicalOutputs(policy.auditDir)
	return policy
}

// canonicalOutputs is what is at the lock's path and at each record's path in
// the default and the declared audit directories, where something is there.
// Nothing found is nothing to compare: the names are still compared.
func (s *Server) canonicalOutputs(declared string) []canonicalFile {
	var found []canonicalFile
	add := func(rel, reason string) {
		if info, err := s.root.Lstat(osPath(rel)); err == nil {
			found = append(found, canonicalFile{info: info, reason: reason})
		}
	}
	add(runtimeLockName, "runtime-lock")
	dirs := append([]string{}, defaultAuditDirs...)
	if declared != "" {
		dirs = append(dirs, declared)
	}
	for _, dir := range dirs {
		for _, name := range auditRecordNames {
			add(path.Join(dir, name), "audit-record")
		}
	}
	return found
}

func isAuditRecordName(name string) bool {
	for _, record := range auditRecordNames {
		if strings.EqualFold(name, record) {
			return true
		}
	}
	return false
}

func (p fileAccessPolicy) isAuditDir(dir string) bool {
	for _, held := range defaultAuditDirs {
		if strings.EqualFold(dir, held) {
			return true
		}
	}
	return p.auditDir != "" && strings.EqualFold(dir, p.auditDir)
}

func (p fileAccessPolicy) readOnlyReason(name string, info fs.FileInfo) string {
	if strings.EqualFold(name, runtimeLockName) {
		return "runtime-lock"
	}
	if isAuditRecordName(path.Base(name)) && (p.auditDirUnknown || p.isAuditDir(path.Dir(name))) {
		return "audit-record"
	}
	if info != nil {
		for _, held := range p.canonical {
			if os.SameFile(info, held.info) {
				return held.reason
			}
		}
		if info.Mode().Perm()&0o222 == 0 {
			return "file-permissions"
		}
	}
	return ""
}

func readOnlyFileMessage(reason string) string {
	switch reason {
	case "runtime-lock":
		return "This lockfile is generated by the runtime. Update it through the pack review and lock workflow."
	case "audit-record":
		return "Audit records are generated by the runtime and cannot be edited in Project files."
	default:
		return "This file is read-only on disk. Change its filesystem permissions before editing it."
	}
}
